version: '3'

services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "3001:3001"
    links:
      - database
  database:
    container_name: database
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_PASSWORD: "pass"
      MYSQL_DATABASE: "up_app_db"
